title: Jochen Thoelen - Portfolio
description: Praktijkgerichte IT-projecten (AD, Windows Server, automatisatie, web).
theme: minima

url: "https://xantar-86.github.io"
baseurl: "/jochen-thoelen.github.io"

header_pages:
  - ad-electro/index.md
  - botje-familyhub/index.md
defaults:
  - scope:
      path: ""
    values:
      layout: default
